package manual

import (
	"context"
	"fmt"
	"time"

	"github.com/Arup3201/torb/auth"
	"github.com/Arup3201/torb/core"
	"github.com/Arup3201/torb/models"
)

const (
	VERIFICATION_TOKEN_DURATION_DEFAULT = 15 * time.Minute
)

/*
Email Service to manage email verification after registration.
*/
type EmailService struct {
	accountRepo *ManualAccountRepository

	VerificationTokenDuration time.Duration
}

func NewEmailService(accountRepo *ManualAccountRepository) *EmailService {

	return &EmailService{
		accountRepo:               accountRepo,
		VerificationTokenDuration: VERIFICATION_TOKEN_DURATION_DEFAULT,
	}
}

/*
Get token for email verification after registration.

Usage:

Attach the token to an URL and send it to the email address.
If the user is valid then they can verify by clicking the link.

NOTE:

It validates if the account is already verified or not. If not, then
only proceed.
*/
func (s *EmailService) GetVerificationToken(ctx context.Context,
	userID string) (string, error) {

	acc, err := s.accountRepo.Get(ctx, userID)
	if err != nil {
		return "", fmt.Errorf("manual account repository get: %w", err)
	}

	if acc.EmailVerified {
		return "", fmt.Errorf("email is already verified: %w", core.ErrInvalidValue)
	}

	token, err := s.generateToken(ctx, acc)
	if err != nil {
		return "", fmt.Errorf("generate token: %w", err)
	}

	return token, nil
}

/*
Get verification token when you only have email

Mainly used when resending the email verification token.
*/
func (s *EmailService) GetVerificationTokenForEmail(ctx context.Context,
	email string) (string, error) {

	acc, err := s.accountRepo.GetByEmail(ctx, email)
	if err != nil {
		return "", fmt.Errorf("manual account repository get: %w", err)
	}

	if acc.EmailVerified {
		return "", fmt.Errorf("email is already verified: %w", core.ErrInvalidValue)
	}

	token, err := s.generateToken(ctx, acc)
	if err != nil {
		return "", fmt.Errorf("generate token: %w", err)
	}

	return token, nil
}

func (s *EmailService) generateToken(ctx context.Context,
	acc models.ManualAccount) (string, error) {

	token, err := auth.GetRandomToken(32)
	if err != nil {
		return "", fmt.Errorf("get random token: %w", err)
	}

	tokenSHA := auth.GetTokenSHA(token)
	tokenExpiresAt := time.Now().UTC().Add(s.VerificationTokenDuration)
	err = s.accountRepo.UpdateVerificationToken(ctx,
		acc,
		tokenSHA,
		tokenExpiresAt)
	if err != nil {
		return "", fmt.Errorf("manual account repository update verification token: %w", err)
	}

	return token, nil
}

/*
Verify email address with token.

Here the token is the one generated by GetVerificationToken
method.

NOTE:

It validates if the token is expired. If not then only
set the email_verified to true.
*/
func (s *EmailService) Verify(ctx context.Context,
	token string) error {

	tokenSHA := auth.GetTokenSHA(token)

	acc, err := s.accountRepo.GetByVerificationToken(ctx, tokenSHA)
	if err != nil {
		return fmt.Errorf("manual account repository get by verification token: %w", err)
	}

	now := time.Now().UTC()
	if acc.VerificationTokenExpiresAt.Sub(now) < 0 {
		return fmt.Errorf("verification token expired: %w", core.ErrInvalidValue)
	}

	err = s.accountRepo.UpdateEmailVerified(ctx, acc, true)
	if err != nil {
		return fmt.Errorf("account repository update email verified: %w", err)
	}

	return nil
}
